version: "3.19"

services:
  db:
    image: postgres:14.5-bullseye
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=CarProject
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=StrongComplicatedPassword123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U spounka -d CarProject" ]
      interval: 2s
      timeout: 3s
      retries: 5

  web:
    build: .
    #    command: gunicorn --bind :8000 --workers 2 CarsProject.wsgi
    command: python3 manage.py runserver
    volumes:
      - .:/code:z
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=CarProject
      - POSTGRES_USER=spounka
      - POSTGRES_PASSWORD=StrongComplicatedPassword123
    depends_on:
      db:
        condition: service_healthy